name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install composer Dependencies
      run: composer install --ignore-platform-reqs
    - name: Install Dependencies (NPM)
      uses: nick-invision/retry@v2
      with:
          timeout_minutes: 5
          max_attempts: 3
          command: npm install

    - name: Prepare
      run: |
          php artisan config:clear
          npm run dev

    - name: Execute Tests
      run: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - name: Generate key
      run: php artisan key:generate
    - name: Setup Project
      run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
          npm run build
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: Run Unit tests
      env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_USERNAME: laravel_test_user
          DB_PASSWORD: super_secret
          DB_DATABASE: laravel_test_db
      run: php artisan test
    - name: Deploy to Server
      if: ${{ success() }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        script: |
          cd apps
          cd laravel-example
          git pull
          npm ci
          npm run prod
          composer i
          php artisan migrate --force
